//
//  NewsFavoriteListPresenter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 23.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteNewsPresentationLogic: AnyObject {
    func presentFavoriteNews(response: FavoriteNews.Fetch.Response)
    func presentAler(error: Error)
}

final class NewsFavoriteListPresenter: FavoriteNewsPresentationLogic  {
    
    weak var viewController: NewsFavoriteListDisplayLogic?
    
    func presentFavoriteNews(response: FavoriteNews.Fetch.Response) {

        var favorites: [FavoriteNews.Fetch.ViewModel.Favorites] = []

        viewController?.displayFavoriteNews(viewModel: FavoriteNews.Fetch.ViewModel(favorites: response.favorites))
    }
    
    func presentAler(error: Error) {
    }
}
