//
//  NewsFavoriteListPresenter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 23.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteNewsPresentationLogic: AnyObject {
    func presentFavoriteNews(response: FavoriteNews.Fetch.Response)
    func presentAler(error: Error)
}

final class NewsFavoriteListPresenter: FavoriteNewsPresentationLogic  {
    
    weak var viewController: NewsFavoriteListDisplayLogic?
    
    func presentFavoriteNews(response: FavoriteNews.Fetch.Response) {

        var favorites: [FavoriteNews.Fetch.ViewModel.Favorites] = []
            response.favorites.forEach {
                if $0.title != nil {
                    favorites.append(FavoriteNews.Fetch.ViewModel.Favorites(title: $0.title,
                                   urlToImage: $0.urlToImage,
                                   publishedAt: $0.publishedAt,
                                   name: $0.name,
                                   content: $0.content,
                                    description: $0.desc))
                }
            }
        
        viewController?.displayFavoriteNews(viewModel: FavoriteNews.Fetch.ViewModel(favorites: favorites))
    }
    
    func presentAler(error: Error) {
    }
}
