//
//  NewsFavoriteListRouter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 23.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

 protocol NewsFavoriteListRoutingLogic {
     func routeToFavoriteDetail(index: Int)
     func routeToNewsList()
}

protocol NewsFavoriteListDataPassing {
      var dataStore: FavoriteListDataStore? { get }
    }
    
class NewsFavoriteListRouter: NewsFavoriteListRoutingLogic, NewsFavoriteListDataPassing  {
    
        weak var viewController: NewsFavoriteListViewController?
          var dataStore: FavoriteListDataStore?
    
    func routeToFavoriteDetail(index: Int) {

        let storyBorad = UIStoryboard(name: "FavoriteDetail", bundle: nil)
        let destVC: FavoriteDetailViewController = storyBorad.instantiateViewController(withIdentifier: "FavoriteDetail") as! FavoriteDetailViewController
        destVC.router?.dataStore?.favoriteItem = dataStore?.favorites?[index]
        
        destVC.modalPresentationStyle = .fullScreen
        viewController?.navigationController?.pushViewController((destVC), animated: true)
    }
    
    func routeToNewsList() {

        let storyBoard = UIStoryboard(name: "NewsList", bundle: nil)
        let destVC: NewsListViewController = storyBoard.instantiateViewController(identifier: "NewsList")
        destVC.modalPresentationStyle = .fullScreen
       
        viewController?.navigationController?.setViewControllers([destVC], animated: true)
    }
}
