//
//  NewsFavoriteListRouter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 23.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

 protocol NewsFavoriteListRoutingLogic {
     func routeToDetailNews(index: Int)
}

protocol NewsFavoriteListDataPassing {
      var dataStore: FavoriteListDataStore? { get }
    }
    
class NewsFavoriteListRouter: NewsFavoriteListRoutingLogic, NewsFavoriteListDataPassing  {
   
        weak var viewController: NewsFavoriteListViewController?
          var dataStore: FavoriteListDataStore?
    
    func routeToDetailNews(index: Int) {

        let storyBorad = UIStoryboard(name: "NewsDetail", bundle: nil)
        let destVC: NewsDetailViewController = storyBorad.instantiateViewController(withIdentifier: "NewsDetailViewController") as! NewsDetailViewController
        destVC.router?.dataStore?.favorites = dataStore?.favorites?[index]
        destVC.isComingFav = true
        destVC.modalPresentationStyle = .fullScreen
        viewController?.navigationController?.pushViewController((destVC), animated: true)

    }
}
