//
//  NewsListPresenter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendDataPresenting: AnyObject {
    func presentNewsList(response: NewsList.Fetch.Response)
    func presentAlert(error: Error)

}

class NewsListPresenter: SendDataPresenting {
    
   weak var viewController: GetNewsDataProtocol?
    
    func presentNewsList(response: NewsList.Fetch.Response) {
        
        var articles: [NewsList.Fetch.ViewModel.News] = []
        response.articles.forEach {
            articles.append(NewsList.Fetch.ViewModel.News(title: $0.title,
                                                          urlToImage: $0.urlToImage,
                                                          publishedAt: $0.publishedAt,
                                                          name: $0.source?.name,
                                                          content: $0.content,
                                                          description: $0.articleDescription))
        }
        viewController?.getNewsData(viewModel: NewsList.Fetch.ViewModel(articles: articles))
    }
    
    func presentAlert(error: Error) {
    }
}
