//
//  NewsListInteractor.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GetNewsListInteracting: AnyObject {
  
    func fetchNews(request: NewsList.Fetch.Request)
}

protocol NewsListDataStore: AnyObject {
    var newsList:  [Article]? { get }
}

class NewsListInteractor: GetNewsListInteracting, NewsListDataStore {
   
    var newsList: [Article]?
    var presenter: SendDataPresenting?
    var worker: NewsListWorkingLogic?
    
    init(worker: NewsListWorkingLogic?) {
        self.worker = worker
    }
    
    func fetchNews(request: NewsList.Fetch.Request) {

        worker?.getNewsList(completion: { result in
            switch result {
            case .success(let response):
                self.newsList = response.articles
                guard let newsList = self.newsList else { return }
                self.presenter?.presentNewsList(response: NewsList.Fetch.Response(articles: newsList))
            case .failure(let error):
                self.presenter?.presentAlert(error: error)
            }
        })
    }
}
