//
//  NewsListWorker.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol NewsListWorkingLogic: AnyObject {
    func getNewsList(completion: @escaping ((Result<NewsListResponse, Error>) -> Void))
}

final class NewsListWorker: NewsListWorkingLogic {
    func getNewsList(completion: @escaping ((Result<NewsListResponse, Error>) -> Void)) {
        Requester().request(model: NewsListResponse.self, parameters: [:]) { result in
            switch result {
            case .httpSuccess(let response):
                completion(.success(response))
            case .httpFail(let error):
                completion(.failure(error))
            }
        }
    }
}
