//
//  NewsListRouter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit

protocol NewsRoutingLogic: AnyObject {
    
    func routeToNewsDetail(index: Int)
    func routeToFavoriteList()
}

protocol NewsDataPassing: AnyObject{
    var dataStore: NewsListDataStore? { get }
}

final class NewsListRouter: NewsRoutingLogic, NewsDataPassing {
    
    
    weak var viewController: NewsListViewController?
    var dataStore: NewsListDataStore?

    func routeToNewsDetail(index: Int) {
        
        let storyBoard = UIStoryboard(name: "NewsDetail", bundle: nil)
        let destVC: NewsDetailViewController = storyBoard.instantiateViewController(identifier: "NewsDetailViewController")
        destVC.router?.dataStore?.articles = (dataStore?.newsList![index])
        destVC.isComingFav = false
        destVC.modalPresentationStyle = .fullScreen
        viewController?.navigationController?.pushViewController(destVC, animated: true)
    }
    
    func routeToFavoriteList() {
        let storyBoard = UIStoryboard(name: "FavoriteList", bundle: nil)
        let destVC: NewsFavoriteListViewController = storyBoard.instantiateViewController(identifier: "FavoriteList")
        destVC.modalPresentationStyle = .fullScreen
        viewController?.navigationController?.pushViewController(destVC, animated: true)
    }
}
