//
//  NewsDetailInteractor.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 17.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailBusinessLogic: AnyObject {
  func fetchNews()
}

protocol NewsDetailDataStore: AnyObject {
    var articles: Article? { get set }
    var favorites: FavoriteNews.Fetch.ViewModel.Favorites? { get set }
}

class NewsDetailInteractor: NewsDetailBusinessLogic, NewsDetailDataStore {
    var favorites: FavoriteNews.Fetch.ViewModel.Favorites?

    var articles: Article?
    var presenter: NewsDetailPresentationLogic?
    var worker: NewsDetailWorker?
    
    init(worker: NewsDetailWorker){
        self.worker = worker
    }
  
  func fetchNews() {
      guard let articles = self.articles else {
          return
      }
      self.presenter?.presentArticle(response: NewsDetail.Fetch.Response(articles: articles))
  }
}
