//
//  NewsDetailRouter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 17.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit

protocol NewsDetailRoutingLogic: AnyObject {
    
    func routeToFavoriteNews()
    
}
 
protocol NewsDetailDataPassing {
  var dataStore: NewsDetailDataStore? { get }
}

final class NewsDetailRouter: NewsDetailRoutingLogic, NewsDetailDataPassing {

    weak var viewController: NewsDetailViewController?
    var dataStore: NewsDetailDataStore?
    
    func routeToFavoriteNews() {
        
        let storyBoard = UIStoryboard(name: "FavoriteList", bundle: nil)
        let destVC: NewsFavoriteListViewController = storyBoard.instantiateViewController(identifier: "FavoriteList")
        destVC.modalPresentationStyle = .fullScreen
        viewController?.navigationController?.pushViewController(destVC, animated: true)
    }
}

