//
//  FavoriteDetailRouter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 15.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteDetailRoutingLogic {
    func routeToWebKit()
}

protocol FavoriteDetailDataPassing {
  var dataStore: FavoriteDetailDataStore? { get }
}

final class FavoriteDetailRouter: FavoriteDetailRoutingLogic, FavoriteDetailDataPassing {

  weak var viewController: FavoriteDetailViewController?
  var dataStore: FavoriteDetailDataStore?
    
    func routeToWebKit() {
        guard let url = URL(string: dataStore?.favoriteItem?.webUrl ?? "") else {
            return
        }
        let vc = WebViewController()
        vc.webView.load(URLRequest(url: url))
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
