//
//  FavoriteDetailInteractor.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 15.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteDetailBusinessLogic: AnyObject {
  func fetchFavorites()
}

protocol FavoriteDetailDataStore: AnyObject {
    var favoriteItem: FavoriteItem? { get set }
}

class FavoriteDetailInteractor: FavoriteDetailBusinessLogic, FavoriteDetailDataStore {
    
    var favoriteItem: FavoriteItem?
    var presenter: FavoriteDetailPresentationLogic?
    var worker: FavoriteDetailWorker?
  
    init(worker: FavoriteDetailWorker){
        self.worker = worker
    }
    
    func fetchFavorites() {
        guard let favoriteItem = self.favoriteItem else {
            return
        }
        self.presenter?.presentSomething(response: FavoriteDetail.Fetch.Response(favItem: favoriteItem))
    }
}
