//
//  FavoriteDetailPresenter.swift
//  BreakingUSNews
//
//  Created by Utku Çetinkaya on 15.12.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteDetailPresentationLogic: AnyObject {
    func presentSomething(response: FavoriteDetail.Fetch.Response)
    func presentAlert(error: Error)
}

final class FavoriteDetailPresenter: FavoriteDetailPresentationLogic {
  weak var viewController: FavoriteDetailDisplayLogic?
  
  func presentSomething(response: FavoriteDetail.Fetch.Response) {
   
      viewController?.displayNews(viewModel: FavoriteDetail.Fetch.ViewModel(
        title: response.favItem.title,
        urlToImage: response.favItem.urlToImage,
        publishedAt: response.favItem.publishedAt,
        name: response.favItem.name,
        content: response.favItem.content ?? "",
        description: response.favItem.desc ?? "",
        url: response.favItem.webUrl))
  }
    
    func presentAlert(error: Error) {
    }
}
